#define PPRINT_targetloc "./../extension/pprint"
#staload "{$PPRINT}/SATS/pprint.sats"
#staload "{$PPRINT}/DATS/pprint_basic.dats"
#staload "{$PPRINT}/DATS/pprint_dynexp0.dats"
#staload "{$PPRINT}/DATS/pprint_dynexp1.dats"
#staload "{$PPRINT}/DATS/pprint_label0.dats"
#staload "{$PPRINT}/DATS/pprint_lexing.dats"
#staload "{$PPRINT}/DATS/pprint_staexp0.dats"
#staload "{$PPRINT}/DATS/pprint_staexp1.dats"
#staload "{$PPRINT}/DATS/pprint_symbol.dats"
#staload "{$PPRINT}/DATS/pread01_dynexp.dats"
